### ISSUE TITLE
mixue秒杀

### ISSUE THREAD

**Issue by long1183551588** [tt619252615/seckill-milk#2]
运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法

**Comment by tt619252615** [comment]
mixue算法变动了，等待更新。

**Comment by XiaoHb233** [comment]
> 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法

手动也是火爆抢不到

**Comment by long1183551588** [comment]
现在url加了验证，有什么思路吗

**Comment by tt619252615** [comment]
> 现在url加了验证，有什么思路吗

正在修改，晚点更新

**Comment by dadad20** [comment]
更新了吗大佬

**Comment by dadad20** [comment]
> 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法

我加入代理api后直接说没获取到ip然后就结束运行了

**Comment by tt619252615** [comment]
> > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> 
> 
> 
> 我加入代理api后直接说没获取到ip然后就结束运行了

这个问题修复了，我还没推送。mixue算法我拿到的js好像不对，测试没通过。

**Comment by dadad20** [comment]
> > > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> > 
> > 
> > 我加入代理api后直接说没获取到ip，然后就结束运行了
> 
> 这个问题修复了，我还没推送。mixue算法我拿到的js好像不对，测试没通过。
好的

**Comment by tt619252615** [comment]
> > > > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> > > 
> > > 
> > > 我加入代理api后直接说没获取到ip，然后就结束运行了
> > 
> > 
> > 这个问题修复了，我还没推送。mixue算法我拿到的js好像不对，测试没通过。
> > 好的



> > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> 
> 我加入代理api后直接说没获取到ip然后就结束运行了

你使用第二个branch试试，我记得在这个branch里面修复了的。

**Comment by dadad20** [comment]
> > > > > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> > > > 
> > > > 
> > > > 我加入代理api后直接说没获取到ip，然后就结束运行了
> > > 
> > > 
> > > 这个问题修复了，我还没推送。mixue算法我拿到的js好像不对，测试没通过。
> > > 好的
> 
> > > 运行发现并未秒杀成功，抓包发现好像mixue resquest url也增加了算法
> > 
> > 
> > 我加入代理api后直接说没获取到ip，然后就结束运行了
> 
> 你使用第二个branch试试，我记得在这个branch里面
好的，试了一下第二个可以

**Comment by tt619252615** [comment]
done

**Comment by tt619252615** [comment]
done
