### ISSUE TITLE
代理总有问题

### ISSUE THREAD

**Issue by XiaoHb233** [tt619252615/seckill-milk#4]
使用的携趣json的ip获取方式

E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py 
2024-08-04 23:56:42.702 | INFO     | __main__:run:191 - [account1] Waiting for start time: 23:56:50
2024-08-04 23:56:42.841 | INFO     | __main__:print_remaining_time:237 - Remaining time: 7.18 seconds
2024-08-04 23:56:42.992 | INFO     | __main__:wait_for_start_time:185 - [account1] Got 1 proxy IPs
2024-08-04 23:56:43.478 | INFO     | __main__:print_remaining_time:237 - Remaining time: 6.55 seconds
.........
2024-08-04 23:56:49.740 | INFO     | __main__:print_remaining_time:237 - Remaining time: 0.28 seconds
2024-08-04 23:56:50.027 | INFO     | __main__:wait_for_start_time:179 - [account1] Starting seckill...
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 259, in <module>
    main(start_time)
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 254, in main
    asyncio.run(manager.run())
  File "E:\IDEA\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "E:\IDEA\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IDEA\python\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 248, in run
    await asyncio.gather(*tasks)
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 225, in worker
    await seckkiller.run()
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 192, in run
    await self.start_seckill()
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 132, in start_seckill
    await self.post_seckill_url(session)
  File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 103, in post_seckill_url
    proxies = f"http://{proxy['ip']}:{proxy['port']}" if proxy else None
                        ~~~~~^^^^^^
KeyError: 'ip'

**Comment by tt619252615** [comment]
> 使用的携趣json的ip获取方式
> 
> 
> 
> 
> 
> E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py 
> 
> 2024-08-04 23:56:42.702 | INFO     | __main__:run:191 - [account1] Waiting for start time: 23:56:50
> 
> 2024-08-04 23:56:42.841 | INFO     | __main__:print_remaining_time:237 - Remaining time: 7.18 seconds
> 
> 2024-08-04 23:56:42.992 | INFO     | __main__:wait_for_start_time:185 - [account1] Got 1 proxy IPs
> 
> 2024-08-04 23:56:43.478 | INFO     | __main__:print_remaining_time:237 - Remaining time: 6.55 seconds
> 
> .........
> 
> 2024-08-04 23:56:49.740 | INFO     | __main__:print_remaining_time:237 - Remaining time: 0.28 seconds
> 
> 2024-08-04 23:56:50.027 | INFO     | __main__:wait_for_start_time:179 - [account1] Starting seckill...
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 259, in <module>
> 
>     main(start_time)
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 254, in main
> 
>     asyncio.run(manager.run())
> 
>   File "E:\IDEA\python\Lib\asyncio\runners.py", line 194, in run
> 
>     return runner.run(main)
> 
>            ^^^^^^^^^^^^^^^^
> 
>   File "E:\IDEA\python\Lib\asyncio\runners.py", line 118, in run
> 
>     return self._loop.run_until_complete(task)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\IDEA\python\Lib\asyncio\base_events.py", line 684, in run_until_complete
> 
>     return future.result()
> 
>            ^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 248, in run
> 
>     await asyncio.gather(*tasks)
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 225, in worker
> 
>     await seckkiller.run()
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 192, in run
> 
>     await self.start_seckill()
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 132, in start_seckill
> 
>     await self.post_seckill_url(session)
> 
>   File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 103, in post_seckill_url
> 
>     proxies = f"http://{proxy['ip']}:{proxy['port']}" if proxy else None
> 
>                         ~~~~~^^^^^^
> 
> KeyError: 'ip'
> 
> 
> 
> 

主程序还是seckill

**Comment by XiaoHb233** [comment]
> > 使用的携趣json的ip获取方式
> > E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py
> > 2024-08-04 23:56:42.702 | INFO     | **main**:run:191 - [account1] Waiting for start time: 23:56:50
> > 2024-08-04 23:56:42.841 | INFO     | **main**:print_remaining_time:237 - Remaining time: 7.18 seconds
> > 2024-08-04 23:56:42.992 | INFO     | **main**:wait_for_start_time:185 - [account1] Got 1 proxy IPs
> > 2024-08-04 23:56:43.478 | INFO     | **main**:print_remaining_time:237 - Remaining time: 6.55 seconds
> > .........
> > 2024-08-04 23:56:49.740 | INFO     | **main**:print_remaining_time:237 - Remaining time: 0.28 seconds
> > 2024-08-04 23:56:50.027 | INFO     | **main**:wait_for_start_time:179 - [account1] Starting seckill...
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 259, in 
> > ```
> > main(start_time)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 254, in main
> > ```
> > asyncio.run(manager.run())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "E:\IDEA\python\Lib\asyncio\runners.py", line 194, in run
> > ```
> > return runner.run(main)
> > 
> >        ^^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "E:\IDEA\python\Lib\asyncio\runners.py", line 118, in run
> > ```
> > return self._loop.run_until_complete(task)
> > 
> >        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "E:\IDEA\python\Lib\asyncio\base_events.py", line 684, in run_until_complete
> > ```
> > return future.result()
> > 
> >        ^^^^^^^^^^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 248, in run
> > ```
> > await asyncio.gather(*tasks)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 225, in worker
> > ```
> > await seckkiller.run()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 192, in run
> > ```
> > await self.start_seckill()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 132, in start_seckill
> > ```
> > await self.post_seckill_url(session)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "C:\Users\Administrator\Desktop\seckill-milk-async\sync_seckill.py", line 103, in post_seckill_url
> > ```
> > proxies = f"http://{proxy['ip']}:{proxy['port']}" if proxy else None
> > 
> >                     ~~~~~^^^^^^
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > KeyError: 'ip'
> 
> 主程序还是seckill

两个seckill都一样，ip可以get到，运行出错，少key

**Comment by tt619252615** [comment]
> sync_seckill.py
sync_seckill.py 你好像运行的这个，你重新pull一下，我昨晚更新了seckill的。应该是没问题的。

**Comment by XiaoHb233** [comment]
> > sync_seckill.py
> > sync_seckill.py 你好像运行的这个，你重新pull一下，我昨晚更新了seckill的。应该是没问题的。

还是不行
立即运行
2024-08-05 13:19:09.174 | INFO     | __mp_main__:run:236 - [account1] Waiting for start time: 00:11:50
2024-08-05 13:19:09.374 | INFO     | __mp_main__:print_remaining_time:291 - Time is up! All processes should start seckill...
2024-08-05 13:19:09.401 | INFO     | __mp_main__:wait_for_start_time:211 - [account1] Starting seckill...
2024-08-05 13:19:09.401 | DEBUG    | __mp_main__:post_seckill_url:118 - [account1] Using proxy: None
2024-08-05 13:19:10.572 | ERROR    | __mp_main__:post_seckill_url:153 - Request failed: Failed to perform, curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
2024-08-05 13:19:10.573 | INFO     | __mp_main__:post_seckill_url:156 - Attempt 1/1 failed. Retrying...
2024-08-05 13:19:10.573 | ERROR    | __mp_main__:post_seckill_url:161 - Reached maximum attempts (1). Stopping requests.
2024-08-05 13:19:10.675 | INFO     | __mp_main__:run:246 - [account1] Seckill finished


定时运行
E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py 
2024-08-05 13:20:26.838 | INFO     | __mp_main__:run:236 - [account1] Waiting for start time: 13:20:30
2024-08-05 13:20:27.024 | INFO     | __mp_main__:print_remaining_time:293 - Remaining time: 2.97 seconds
2024-08-05 13:20:27.248 | INFO     | __mp_main__:wait_for_start_time:224 - [account1] Got 1 proxy IPs
2024-08-05 13:20:27.688 | INFO     | __mp_main__:print_remaining_time:293 - Remaining time: 2.30 seconds
2024-08-05 13:20:28.376 | INFO     | __mp_main__:print_remaining_time:293 - Remaining time: 1.61 seconds
2024-08-05 13:20:29.046 | INFO     | __mp_main__:print_remaining_time:293 - Remaining time: 0.94 seconds
2024-08-05 13:20:29.713 | INFO     | __mp_main__:print_remaining_time:293 - Remaining time: 0.28 seconds
2024-08-05 13:20:30.134 | INFO     | __mp_main__:wait_for_start_time:211 - [account1] Starting seckill...
Exception in thread Thread-1 (start_seckill):
Traceback (most recent call last):
  File "E:\IDEA\python\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "E:\IDEA\python\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 169, in start_seckill
    self.post_seckill_url()
  File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 106, in post_seckill_url
    f"http://{proxy['ip']}:{proxy['port']}"
              ~~~~~^^^^^^
KeyError: 'ip'
2024-08-05 13:20:30.138 | INFO     | __mp_main__:run:246 - [account1] Seckill finished

**Comment by tt619252615** [comment]
> > > sync_seckill.py
> > > sync_seckill.py 你好像运行的这个，你重新pull一下，我昨晚更新了seckill的。应该是没问题的。
> 
> 还是不行 立即运行 2024-08-05 13:19:09.174 | INFO | **mp_main**:run:236 - [account1] Waiting for start time: 00:11:50 2024-08-05 13:19:09.374 | INFO | **mp_main**:print_remaining_time:291 - Time is up! All processes should start seckill... 2024-08-05 13:19:09.401 | INFO | **mp_main**:wait_for_start_time:211 - [account1] Starting seckill... 2024-08-05 13:19:09.401 | DEBUG | **mp_main**:post_seckill_url:118 - [account1] Using proxy: None 2024-08-05 13:19:10.572 | ERROR | **mp_main**:post_seckill_url:153 - Request failed: Failed to perform, curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 2024-08-05 13:19:10.573 | INFO | **mp_main**:post_seckill_url:156 - Attempt 1/1 failed. Retrying... 2024-08-05 13:19:10.573 | ERROR | **mp_main**:post_seckill_url:161 - Reached maximum attempts (1). Stopping requests. 2024-08-05 13:19:10.675 | INFO | **mp_main**:run:246 - [account1] Seckill finished
> 
> 定时运行 E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py 2024-08-05 13:20:26.838 | INFO | **mp_main**:run:236 - [account1] Waiting for start time: 13:20:30 2024-08-05 13:20:27.024 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 2.97 seconds 2024-08-05 13:20:27.248 | INFO | **mp_main**:wait_for_start_time:224 - [account1] Got 1 proxy IPs 2024-08-05 13:20:27.688 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 2.30 seconds 2024-08-05 13:20:28.376 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 1.61 seconds 2024-08-05 13:20:29.046 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 0.94 seconds 2024-08-05 13:20:29.713 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 0.28 seconds 2024-08-05 13:20:30.134 | INFO | **mp_main**:wait_for_start_time:211 - [account1] Starting seckill... Exception in thread Thread-1 (start_seckill): Traceback (most recent call last): File "E:\IDEA\python\Lib\threading.py", line 1073, in _bootstrap_inner self.run() File "E:\IDEA\python\Lib\threading.py", line 1010, in run self._target(*self._args, **self._kwargs) File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 169, in start_seckill self.post_seckill_url() File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 106, in post_seckill_url f"http://{proxy['ip']}:{proxy['port']}" ~~~~~^^^^^^ KeyError: 'ip' 2024-08-05 13:20:30.138 | INFO | **mp_main**:run:246 - [account1] Seckill finished

我晚点看看，这里可能每个代理商的json格式不统一。

**Comment by XiaoHb233** [comment]
> > > > sync_seckill.py
> > > > sync_seckill.py 你好像运行的这个，你重新pull一下，我昨晚更新了seckill的。应该是没问题的。
> > 
> > 
> > 还是不行 立即运行 2024-08-05 13:19:09.174 | INFO | **mp_main**:run:236 - [account1] Waiting for start time: 00:11:50 2024-08-05 13:19:09.374 | INFO | **mp_main**:print_remaining_time:291 - Time is up! All processes should start seckill... 2024-08-05 13:19:09.401 | INFO | **mp_main**:wait_for_start_time:211 - [account1] Starting seckill... 2024-08-05 13:19:09.401 | DEBUG | **mp_main**:post_seckill_url:118 - [account1] Using proxy: None 2024-08-05 13:19:10.572 | ERROR | **mp_main**:post_seckill_url:153 - Request failed: Failed to perform, curl: (28) Operation timed out after 1003 milliseconds with 0 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 2024-08-05 13:19:10.573 | INFO | **mp_main**:post_seckill_url:156 - Attempt 1/1 failed. Retrying... 2024-08-05 13:19:10.573 | ERROR | **mp_main**:post_seckill_url:161 - Reached maximum attempts (1). Stopping requests. 2024-08-05 13:19:10.675 | INFO | **mp_main**:run:246 - [account1] Seckill finished
> > 定时运行 E:\IDEA\python\python.exe C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py 2024-08-05 13:20:26.838 | INFO | **mp_main**:run:236 - [account1] Waiting for start time: 13:20:30 2024-08-05 13:20:27.024 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 2.97 seconds 2024-08-05 13:20:27.248 | INFO | **mp_main**:wait_for_start_time:224 - [account1] Got 1 proxy IPs 2024-08-05 13:20:27.688 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 2.30 seconds 2024-08-05 13:20:28.376 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 1.61 seconds 2024-08-05 13:20:29.046 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 0.94 seconds 2024-08-05 13:20:29.713 | INFO | **mp_main**:print_remaining_time:293 - Remaining time: 0.28 seconds 2024-08-05 13:20:30.134 | INFO | **mp_main**:wait_for_start_time:211 - [account1] Starting seckill... Exception in thread Thread-1 (start_seckill): Traceback (most recent call last): File "E:\IDEA\python\Lib\threading.py", line 1073, in _bootstrap_inner self.run() File "E:\IDEA\python\Lib\threading.py", line 1010, in run self._target(*self._args, **self._kwargs) File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 169, in start_seckill self.post_seckill_url() File "C:\Users\Administrator\Desktop\seckill-milk-async\seckill.py", line 106, in post_seckill_url f"http://{proxy['ip']}:{proxy['port']}" ~~~~~^^^^^^ KeyError: 'ip' 2024-08-05 13:20:30.138 | INFO | **mp_main**:run:246 - [account1] Seckill finished
> 
> 我晚点看看，这里可能每个代理商的json格式不统一。

楼主用的哪家代理，我去试试

**Comment by tt619252615** [comment]
> 主用的哪家代理，我去试试

多米

**Comment by tt619252615** [comment]
done
